SELECT
    OUTS.ANIMAL_ID,
    OUTS.NAME
FROM 
    ANIMAL_INS AS INS,
    ANIMAL_OUTS AS OUTS
WHERE   
    INS.ANIMAL_ID = OUTS.ANIMAL_ID
ORDER BY
    DATEDIFF(OUTS.DATETIME, INS.DATETIME) DESC
LIMIT  
    2;