SELECT
    BOOK.CATEGORY,
    SUM(BS.SALES) AS TOTAL_SALES
FROM    
    BOOK 
JOIN 
    BOOK_SALES AS BS
ON
    BOOK.BOOK_ID = BS.BOOK_ID
WHERE 
    BS.SALES_DATE LIKE '2022-01%'
GROUP BY
    BOOK.CATEGORY
ORDER BY
    BOOK.CATEGORY ASC;